{% set name = "espaloma_charge" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/espaloma_charge/archive/v{{ version }}.tar.gz
  sha256: 622aaede2d4086d4646ee8ff92f58e441eecb719fbc4557bad5a99db1349f5cf
  patches:
    - 000-update-versioneer.patch

build:
  entry_points:
    - espaloma_charge=espaloma_charge.cli:espaloma_charge
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - pytorch
    - rdkit
    - dgl ~=2.0

test:
  imports:
    - espaloma_charge
  commands:
    - pip check
    - espaloma_charge --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/choderalab/espaloma_charge
  summary: Standalone charge assignment from Espaloma framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
    - yuanqing-wang
    - ijpulidos
